version: '3.8'

services:
  api:
    environment:
      DATABASE_URL: postgresql://lufraga:182077@duo-finance-pg:5432/duo-finance-db
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
